// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOLUQoI9KG4OhP8vP9PpsutvQt2YTb5bE',
    appId: '1:909619182361:web:ca1eae5bb47b7c02efe388',
    messagingSenderId: '909619182361',
    projectId: 'learning-firebase-1b0cb',
    authDomain: 'learning-firebase-1b0cb.firebaseapp.com',
    storageBucket: 'learning-firebase-1b0cb.firebasestorage.app',
    measurementId: 'G-S670Y7CSLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQQT6sB9TwU09wArI9Nhuw1tr6w18isbE',
    appId: '1:909619182361:android:98017b2eede70e17efe388',
    messagingSenderId: '909619182361',
    projectId: 'learning-firebase-1b0cb',
    storageBucket: 'learning-firebase-1b0cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYPJF5wbkMSgKtb6e0tMttvO3p4gQd-N4',
    appId: '1:909619182361:ios:234af5d3a80804b2efe388',
    messagingSenderId: '909619182361',
    projectId: 'learning-firebase-1b0cb',
    storageBucket: 'learning-firebase-1b0cb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearning',
  );

}